version: "3.9"
services:
  postgres-local:
    image: postgres:latest
    container_name: postgres-local
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./app.env
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8010
    ports:
      - "8010:8010"
    depends_on:
      - postgres-local


volumes:
  db:
