// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Cause struct {
	ID            int32          `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	Goal          sql.NullString `json:"goal"`
	CurrentAmount sql.NullString `json:"current_amount"`
	StartDate     sql.NullTime   `json:"start_date"`
	EndDate       sql.NullTime   `json:"end_date"`
	Status        sql.NullString `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Donation struct {
	ID           int32          `json:"id"`
	UserID       sql.NullInt32  `json:"user_id"`
	CauseID      sql.NullInt32  `json:"cause_id"`
	TeamID       sql.NullInt32  `json:"team_id"`
	Amount       sql.NullString `json:"amount"`
	DonationType sql.NullString `json:"donation_type"`
	Status       sql.NullString `json:"status"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Leaderboard struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Type      sql.NullString `json:"type"`
	StartDate sql.NullTime   `json:"start_date"`
	EndDate   sql.NullTime   `json:"end_date"`
}

type LeaderboardEntry struct {
	LeaderboardID int32          `json:"leaderboard_id"`
	UserID        int32          `json:"user_id"`
	TeamID        int32          `json:"team_id"`
	Score         sql.NullString `json:"score"`
	Rank          sql.NullInt32  `json:"rank"`
}

type Team struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID           int32          `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type UserTeam struct {
	UserID int32  `json:"user_id"`
	TeamID int32  `json:"team_id"`
	Role   string `json:"role"`
}

type UserToken struct {
	ID        int32         `json:"id"`
	UserID    sql.NullInt32 `json:"user_id"`
	Token     string        `json:"token"`
	Expiry    time.Time     `json:"expiry"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}
